name: Run Laravel Package Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=10s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP, with Composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
        tools: composer:v2

    - name: Install Laravel and Marketplace Packages
      run: |
        composer create-project --prefer-dist laravel/laravel laravel
        cd laravel
        composer config repositories.self path ../
        composer require danialhatami/simple-marketplace:dev-master --prefer-source --no-update
        composer update

    - name: Set up Laravel Environment
      run: |
        cd laravel
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=password" >> .env

    - name: Run Tests
      run: |
        cd laravel
        php artisan simple-marketplace:install
        php artisan migrate
        php artisan test
        ./vendor/bin/phpunit ./vendor/danialhatami/simple-marketplace/src/Tests/
